package com.callmangement.ui.ins_weighing_scale.model.fps

class DetailByFpsData(
    var isStatus: Boolean,
    var message: String,
    var districtId: Int,
    @JvmField var fpscode: String,
    var updatedBy: Any,
    @JvmField var districtName: String,
    @JvmField var dealerName: String,
    @JvmField var blockName: String,
    var ticketNo: Any,
    var last_Remark: Any,
    var remarks: Any,
    var tranDateStr: Any,
    var isActive: Boolean,
    var updatedOn: Any,
    var longitude: Any,
    var createdOn: Any,
    var latitude: Any,
    var shopAddress: Any,
    var tranDate: Any,
    var deliveryId: Any,
    @JvmField var fpsdeviceCode: String,
    var deliveredBy: Any,
    var images: Any,
    var last_TicketStatus: Any,
    @JvmField var weighingScaleModelName: Any,
    @JvmField var irisScannerModelName: Any,
    var isDeliverdIRIS: Boolean,
    var isDeliverdWeighingScale: Boolean,
    @JvmField var weighingScaleSerialNo: Any,
    @JvmField var irisScannerSerialNo: Any,
    var last_TicketStatusId: Any,
    @JvmField var dealerMobileNo: String,
    var deliveredOn: Any,
    var otp: Any,
    var userID: Any,
    var imagesDetail: Any
)
