package com.callmangement.ui.ins_weighing_scale.model.Installed

import java.io.Serializable

class InstalledDatum(
    var isStatus: Boolean,
    var message: String,
    var isDeliverdIRIS: Boolean,
    var otp: String,
    var images: String,
    var imagesDetail: String,
    @JvmField var dealerMobileNo: String,
    @JvmField var irisScannerSerialNo: String,
    var irisScannerModelId: String,
    var winghingScaleDeliveredOn: String,
    var isDeliverdWeighingScale: Boolean,
    @JvmField var weighingScaleModelName: String,
    var irisScannerModelName: String,
    @JvmField var weighingScaleSerialNo: String,
    var irisDeviceType: String,
    @JvmField var irisDeviceModel: String,
    var deliveryRemark: String,
    var installationBy: Int,
    @JvmField var winghingScaleDeliveredOnStr: String,
    var irisDeviceModelId: Int,
    var last_TicketStatusId: Int,
    @JvmField var installationOnStr: String,
    var weighingScaleDeliveredBy: Int,
    var irisDeviceTypeId: Int,
    @JvmField var last_TicketStatus: String,
    var installationRemark: String,
    var irisdeliveredOnStr: String,
    var deliveredByName: String,
    var isActive: Boolean,
    var weighingScaleModelId: String,
    var irisdeliveredOn: String,
    var installationOn: String,
    var last_Remark: String,
    @JvmField var dealerName: String,
    @JvmField var ticketNo: String,
    var remarks: String,
    @JvmField var blockName: String,
    @JvmField var districtId: Int,
    var deviceTypeId: Int,
    @JvmField var fpscode: String,
    var userID: String,
    var blockId: String,
    var fpsdeviceCode: String,
    @JvmField var districtName: String,
    var updatedBy: Int,
    @JvmField var deviceModelId: Int,
    var deviceModel: String,
    var tranDate: String,
    @JvmField var shopAddress: String,
    var deviceType: String,
    @JvmField var deliveryId: Int,
    var tranDateStr: String,
    var latitude: String,
    var longitude: String,
    var createdOn: String,
    var updatedOn: String
) : Serializable
