package com.callmangement.model.weighingDeliveryDetail

class weighingDeliveryData(
    var isStatus: Boolean,
    var message: String,
    var districtId: Int,
    var fpscode: String,
    var ticketNo: String,
    var districtName: String,
    var userID: Any,
    var blockId: Any,
    var fpsdeviceCode: String,
    var dealerName: String,
    var blockName: String,
    var updatedBy: Int,
    var last_Remark: String,
    var isActive: Boolean,
    var remarks: Any,
    var tranDateStr: Any,
    var shopAddress: String,
    var latitude: String,
    var longitude: String,
    var images: Any,
    var otp: Any,
    var deliveryId: Int,
    var createdOn: Any,
    var updatedOn: Any,
    var installationOnStr: Any,
    var installationOn: Any,
    var last_TicketStatus: String,
    var installationBy: Int,
    var irisdeliveredOn: Any,
    var deliveryRemark: String,
    var installationRemark: Any,
    var weighingScaleDeliveredBy: Int,
    var weighingScaleModelName: String,
    var dealerMobileNo: String,
    var irisdeliveredOnStr: Any,
    @JvmField var weighingScaleSerialNo: String,
    var winghingScaleDeliveredOnStr: String,
    var tranDate: Any,
    @JvmField var imagesDetail: ArrayList<weighingDeliveryImagesDetail>,
    var isDeliverdIRIS: Boolean,
    var isDeliverdWeighingScale: Boolean,
    var irisScannerSerialNo: Any,
    var irisScannerModelName: Any,
    var winghingScaleDeliveredOn: Any,
    var last_TicketStatusId: Int
)
